services:
  frontend:
    build: .
    container_name: frontend
    volumes:
      - './src:/knife-market/src'
      - './index.html:/knife-market/index.html'
      - './vite.config.ts:/knife-market/vite.config.ts'
    ports:
      - 5173:5173
    stdin_open: true
    command: bash -c "npm install && npm run dev"
